### ISSUE TITLE
IU Issue

### ISSUE THREAD

**Issue by rmcohen3** [purdy/cachestatus-firefox#1]
Hello,

I have the RAM cache set to a value (200M) and the disk cache set to 0. However, the UI in the status bar displays an identical >0 value for both caches. Please assist.

Firefox 35.0.1

Thank you,
Robert

**Comment by purdy** [comment]
I'm sorry I wasn't able to resolve this issue at the time. Given its age (and probably irrelevance at this point), I'm going to close this.
