### ISSUE TITLE
Max Disk Cache Vaule Resets

### ISSUE THREAD

**Issue by jfiveNYC** [purdy/cachestatus-firefox#3]
After setting the maximum disk cache value in the preferences pane or in about:config, that value will, at random, reset to the default value of 354000KB.

Firefox v42
OS X 10.11.2 (El Capitan)
Mackbook Pro 17" early-2009
Intel core-2-duo, 8GB RAM
Cache Status v0.9.0 (removed and reinstalled several times)

**Comment by purdy** [comment]
I'm sorry I wasn't able to resolve this issue at the time. Given its age (and probably irrelevance at this point), I'm going to close this.
