### ISSUE TITLE
Missing UI

### ISSUE THREAD

**Issue by Uh-Clem** [purdy/cachestatus-firefox#4]
Mac OS X 10.11.4 / Firefox 45.0.2  CacheStatus 0.9.1  -  Cache status/clear buttons no longer show up on address or status bar regardless of preference settings (Original / Icons / UI on Status bar / Force UI on Status bar).  Tried going back to version 0.8.7.1-signed but no difference.

**Comment by andy-portmen** [comment]
Maybe there is a conflict with another extension. Can you confirm this by installing the extension on a clean profile; http://blog.add0n.com/2016/01/30/how-to-use-firefox-profile-manager.html

**Comment by grahamperrin** [comment]
## Workaround

1. install [Status-4-Evar](https://addons.mozilla.org/addon/status-4-evar/)
2. restart the browser. 

You'll find Cache Status items in the status bar at the foot of the window. 

Tested with Waterfox 56.0.1 on FreeBSD-CURRENT: 

![2017-12-30 16 18 23](https://user-images.githubusercontent.com/192271/34455746-3f0e2a8e-ed7d-11e7-86ea-fb5cd36f9afd.png)

– so the workaround should also be good for Firefox 56.0.2.

**Comment by purdy** [comment]
Closing this issue. Thanks for the workaround, @grahamperrin! :)
