### ISSUE TITLE
Cache Status: Update Stats not working in some situations

### ISSUE THREAD

**Issue by grahamperrin** [purdy/cachestatus-firefox#5]
Automatic updates disabled. 

When I first open Waterfox 56.0.1 with just one window, I can get a measurement. 

After restoring a large session – more than 1,500 tabs – I can no longer get a measurement. In the first window, the previous measurement disappears.

**Comment by purdy** [comment]
That's quite a use case (>1,500 tabs and Waterfox). This add-on only supports Firefox, but ending at version 56 (v57 removed how the add-on accesses the cache system).
