### ISSUE TITLE
Unable to update extension from v 0.9.3 to version 3.1

### ISSUE THREAD

**Issue by martinym** [purdy/cachestatus-firefox#6]
This has been a problem for many months, maybe even a year. 
I'm now using Firefox ESR 52.7.3 (64-bit) and the problem persists (see screenshot).
![clear-cache-update-error-message](https://user-images.githubusercontent.com/2790408/38109282-82acb5ac-334c-11e8-9bad-01f4a67ded3a.jpg)

Have considered completely removing it and trying to reinstall, but I don't know where to get the latest version to download.

**Comment by purdy** [comment]
Hi Martin,

I believe you're looking for the Clear Cache add on. This is Cache Status.

**Comment by martinym** [comment]
Yes, you are correct. Sorry for the mistake.
